stages:
  - test

jobpre:
  image: alpine
  stage: test
  run:
    - name: init
      script: "/sbin/apk update && /sbin/apk add clang++ lld cmake openjdk21 maven"
    - name: build
      script: "mvn install"
    - name: test
      script: "./tests.sh"